services:
  main:
    container_name: application
    build : .
    depends_on:
      - postgres_db
    ports:
      - 8000:8000
    env_file:
      - ".env"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres_db:
    container_name: postgres_db
    image: postgres
    environment:
      POSTGRES_PASSWORD: adminPWDsupsersecure
    ports:
      - 5432